//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDocument
    {
        public int Id { get; set; }
        public string DocumentTitle { get; set; }
        public string DocumentType { get; set; }
        public string DocumentPath { get; set; }
        public string CRNumber { get; set; }
    }
}
